var annotated_dup =
[
    [ "cfem_diffusion", "d3/d65/namespacecfem__diffusion.html", [
      [ "Boundary", "d6/dc1/classcfem__diffusion_1_1_boundary.html", "d6/dc1/classcfem__diffusion_1_1_boundary" ],
      [ "Solver", "de/dba/classcfem__diffusion_1_1_solver.html", "de/dba/classcfem__diffusion_1_1_solver" ]
    ] ],
    [ "chi_data_types", "d5/d1b/namespacechi__data__types.html", [
      [ "ByteArray", "d5/d5b/classchi__data__types_1_1_byte_array.html", "d5/d5b/classchi__data__types_1_1_byte_array" ],
      [ "NDArray", "d2/d5d/classchi__data__types_1_1_n_d_array.html", "d2/d5d/classchi__data__types_1_1_n_d_array" ],
      [ "Varying", "d8/d30/classchi__data__types_1_1_varying.html", "d8/d30/classchi__data__types_1_1_varying" ]
    ] ],
    [ "chi_diffusion", "de/d73/namespacechi__diffusion.html", [
      [ "Boundary", "d7/dae/classchi__diffusion_1_1_boundary.html", "d7/dae/classchi__diffusion_1_1_boundary" ],
      [ "BoundaryDirichlet", "de/d2e/classchi__diffusion_1_1_boundary_dirichlet.html", "de/d2e/classchi__diffusion_1_1_boundary_dirichlet" ],
      [ "BoundaryReflecting", "d1/d0c/classchi__diffusion_1_1_boundary_reflecting.html", "d1/d0c/classchi__diffusion_1_1_boundary_reflecting" ],
      [ "BoundaryRobin", "d6/d58/classchi__diffusion_1_1_boundary_robin.html", "d6/d58/classchi__diffusion_1_1_boundary_robin" ],
      [ "Solver", "d6/d32/classchi__diffusion_1_1_solver.html", "d6/d32/classchi__diffusion_1_1_solver" ]
    ] ],
    [ "chi_graph", "d3/d00/namespacechi__graph.html", [
      [ "DirectedGraph", "dc/d15/classchi__graph_1_1_directed_graph.html", "dc/d15/classchi__graph_1_1_directed_graph" ],
      [ "GraphVertex", "da/d1d/structchi__graph_1_1_graph_vertex.html", "da/d1d/structchi__graph_1_1_graph_vertex" ]
    ] ],
    [ "chi_math", "dc/d58/namespacechi__math.html", [
      [ "finite_element", "d3/d84/namespacechi__math_1_1finite__element.html", [
        [ "FaceQuadraturePointData", "d5/df3/classchi__math_1_1finite__element_1_1_face_quadrature_point_data.html", "d5/df3/classchi__math_1_1finite__element_1_1_face_quadrature_point_data" ],
        [ "InternalQuadraturePointData", "d5/da1/classchi__math_1_1finite__element_1_1_internal_quadrature_point_data.html", "d5/da1/classchi__math_1_1finite__element_1_1_internal_quadrature_point_data" ],
        [ "UnitIntegralData", "de/d0d/classchi__math_1_1finite__element_1_1_unit_integral_data.html", "de/d0d/classchi__math_1_1finite__element_1_1_unit_integral_data" ]
      ] ],
      [ "PETScUtils", "dc/d29/namespacechi__math_1_1_p_e_t_sc_utils.html", [
        [ "GhostVecLocalRaw", "d8/d4e/structchi__math_1_1_p_e_t_sc_utils_1_1_ghost_vec_local_raw.html", "d8/d4e/structchi__math_1_1_p_e_t_sc_utils_1_1_ghost_vec_local_raw" ],
        [ "PETScSolverSetup", "d1/d25/structchi__math_1_1_p_e_t_sc_utils_1_1_p_e_t_sc_solver_setup.html", "d1/d25/structchi__math_1_1_p_e_t_sc_utils_1_1_p_e_t_sc_solver_setup" ]
      ] ],
      [ "SimplifiedLDFESQ", "dd/d56/namespacechi__math_1_1_simplified_l_d_f_e_s_q.html", [
        [ "BaseFunctor", "de/dc6/structchi__math_1_1_simplified_l_d_f_e_s_q_1_1_base_functor.html", "de/dc6/structchi__math_1_1_simplified_l_d_f_e_s_q_1_1_base_functor" ],
        [ "FUNCTION_WEIGHT_FROM_RHO", "d3/d82/structchi__math_1_1_simplified_l_d_f_e_s_q_1_1_f_u_n_c_t_i_o_n___w_e_i_g_h_t___f_r_o_m___r_h_o.html", "d3/d82/structchi__math_1_1_simplified_l_d_f_e_s_q_1_1_f_u_n_c_t_i_o_n___w_e_i_g_h_t___f_r_o_m___r_h_o" ],
        [ "Quadrature", "d3/ddf/classchi__math_1_1_simplified_l_d_f_e_s_q_1_1_quadrature.html", "d3/ddf/classchi__math_1_1_simplified_l_d_f_e_s_q_1_1_quadrature" ],
        [ "SphericalQuadrilateral", "d6/dfa/structchi__math_1_1_simplified_l_d_f_e_s_q_1_1_spherical_quadrilateral.html", "d6/dfa/structchi__math_1_1_simplified_l_d_f_e_s_q_1_1_spherical_quadrilateral" ]
      ] ],
      [ "AngularQuadrature", "d8/dd9/classchi__math_1_1_angular_quadrature.html", "d8/dd9/classchi__math_1_1_angular_quadrature" ],
      [ "AngularQuadratureCustom", "d8/dd8/classchi__math_1_1_angular_quadrature_custom.html", "d8/dd8/classchi__math_1_1_angular_quadrature_custom" ],
      [ "AngularQuadratureProdCustom", "db/d47/classchi__math_1_1_angular_quadrature_prod_custom.html", "db/d47/classchi__math_1_1_angular_quadrature_prod_custom" ],
      [ "AngularQuadratureProdGL", "d5/d32/classchi__math_1_1_angular_quadrature_prod_g_l.html", "d5/d32/classchi__math_1_1_angular_quadrature_prod_g_l" ],
      [ "AngularQuadratureProdGLC", "d6/d28/classchi__math_1_1_angular_quadrature_prod_g_l_c.html", "d6/d28/classchi__math_1_1_angular_quadrature_prod_g_l_c" ],
      [ "AngularQuadratureProdGLL", "d9/d87/classchi__math_1_1_angular_quadrature_prod_g_l_l.html", "d9/d87/classchi__math_1_1_angular_quadrature_prod_g_l_l" ],
      [ "CDFSampler", "d5/ddf/classchi__math_1_1_c_d_f_sampler.html", "d5/ddf/classchi__math_1_1_c_d_f_sampler" ],
      [ "CellFVValues", "d9/d9a/classchi__math_1_1_cell_f_v_values.html", "d9/d9a/classchi__math_1_1_cell_f_v_values" ],
      [ "CellMapping", "d8/d08/classchi__math_1_1_cell_mapping.html", "d8/d08/classchi__math_1_1_cell_mapping" ],
      [ "CellMappingFE_PWL", "d7/d3f/classchi__math_1_1_cell_mapping_f_e___p_w_l.html", "d7/d3f/classchi__math_1_1_cell_mapping_f_e___p_w_l" ],
      [ "CurvilinearAngularQuadrature", "d9/dc1/classchi__math_1_1_curvilinear_angular_quadrature.html", "d9/dc1/classchi__math_1_1_curvilinear_angular_quadrature" ],
      [ "CylindricalAngularQuadrature", "d8/d60/classchi__math_1_1_cylindrical_angular_quadrature.html", "d8/d60/classchi__math_1_1_cylindrical_angular_quadrature" ],
      [ "DynamicMatrix", "df/d4b/classchi__math_1_1_dynamic_matrix.html", "df/d4b/classchi__math_1_1_dynamic_matrix" ],
      [ "DynamicVector", "db/d08/classchi__math_1_1_dynamic_vector.html", "db/d08/classchi__math_1_1_dynamic_vector" ],
      [ "GolubFischer", "d7/d89/classchi__math_1_1_golub_fischer.html", "d7/d89/classchi__math_1_1_golub_fischer" ],
      [ "LinearSolver", "dd/d52/classchi__math_1_1_linear_solver.html", "dd/d52/classchi__math_1_1_linear_solver" ],
      [ "LinearSolverContext", "d0/dfb/structchi__math_1_1_linear_solver_context.html", "d0/dfb/structchi__math_1_1_linear_solver_context" ],
      [ "NonLinearFunction", "d6/dc4/classchi__math_1_1_non_linear_function.html", "d6/dc4/classchi__math_1_1_non_linear_function" ],
      [ "NonLinearSolver", "dd/deb/classchi__math_1_1_non_linear_solver.html", "dd/deb/classchi__math_1_1_non_linear_solver" ],
      [ "NonLinearSolverContext", "d2/d14/structchi__math_1_1_non_linear_solver_context.html", "d2/d14/structchi__math_1_1_non_linear_solver_context" ],
      [ "PolygonMappingFE_PWL", "dd/d08/classchi__math_1_1_polygon_mapping_f_e___p_w_l.html", "dd/d08/classchi__math_1_1_polygon_mapping_f_e___p_w_l" ],
      [ "PolygonMappingFE_PWL_Cylindrical", "d2/db9/classchi__math_1_1_polygon_mapping_f_e___p_w_l___cylindrical.html", "d2/db9/classchi__math_1_1_polygon_mapping_f_e___p_w_l___cylindrical" ],
      [ "PolyhedronMappingFE_PWL", "d5/dfe/classchi__math_1_1_polyhedron_mapping_f_e___p_w_l.html", "d5/dfe/classchi__math_1_1_polyhedron_mapping_f_e___p_w_l" ],
      [ "PreconditionerContext", "d6/db8/structchi__math_1_1_preconditioner_context.html", "d6/db8/structchi__math_1_1_preconditioner_context" ],
      [ "ProductQuadrature", "d5/df7/classchi__math_1_1_product_quadrature.html", "d5/df7/classchi__math_1_1_product_quadrature" ],
      [ "Quadrature", "d3/dbf/classchi__math_1_1_quadrature.html", "d3/dbf/classchi__math_1_1_quadrature" ],
      [ "QuadratureConical", "da/d37/classchi__math_1_1_quadrature_conical.html", "da/d37/classchi__math_1_1_quadrature_conical" ],
      [ "QuadratureGaussChebyshev", "d4/de5/classchi__math_1_1_quadrature_gauss_chebyshev.html", "d4/de5/classchi__math_1_1_quadrature_gauss_chebyshev" ],
      [ "QuadratureGaussLegendre", "d3/d07/classchi__math_1_1_quadrature_gauss_legendre.html", "d3/d07/classchi__math_1_1_quadrature_gauss_legendre" ],
      [ "QuadratureHexahedron", "d2/d67/classchi__math_1_1_quadrature_hexahedron.html", "d2/d67/classchi__math_1_1_quadrature_hexahedron" ],
      [ "QuadratureJacobi", "d4/d17/classchi__math_1_1_quadrature_jacobi.html", "d4/d17/classchi__math_1_1_quadrature_jacobi" ],
      [ "QuadratureLine", "d8/d8d/classchi__math_1_1_quadrature_line.html", "d8/d8d/classchi__math_1_1_quadrature_line" ],
      [ "QuadraturePointPhiTheta", "dc/d9c/structchi__math_1_1_quadrature_point_phi_theta.html", "dc/d9c/structchi__math_1_1_quadrature_point_phi_theta" ],
      [ "QuadratureQuadrilateral", "da/d04/classchi__math_1_1_quadrature_quadrilateral.html", "da/d04/classchi__math_1_1_quadrature_quadrilateral" ],
      [ "QuadratureTetrahedron", "d8/d57/classchi__math_1_1_quadrature_tetrahedron.html", "d8/d57/classchi__math_1_1_quadrature_tetrahedron" ],
      [ "QuadratureTriangle", "d0/d61/classchi__math_1_1_quadrature_triangle.html", "d0/d61/classchi__math_1_1_quadrature_triangle" ],
      [ "RandomNumberGenerator", "d9/d55/classchi__math_1_1_random_number_generator.html", "d9/d55/classchi__math_1_1_random_number_generator" ],
      [ "SlabMappingFE_PWL", "df/dc2/classchi__math_1_1_slab_mapping_f_e___p_w_l.html", "df/dc2/classchi__math_1_1_slab_mapping_f_e___p_w_l" ],
      [ "SlabMappingFE_PWL_Cylindrical", "d2/d9d/classchi__math_1_1_slab_mapping_f_e___p_w_l___cylindrical.html", "d2/d9d/classchi__math_1_1_slab_mapping_f_e___p_w_l___cylindrical" ],
      [ "SlabMappingFE_PWL_Spherical", "d4/dcb/classchi__math_1_1_slab_mapping_f_e___p_w_l___spherical.html", "d4/dcb/classchi__math_1_1_slab_mapping_f_e___p_w_l___spherical" ],
      [ "SparseMatrix", "de/d51/classchi__math_1_1_sparse_matrix.html", "de/d51/classchi__math_1_1_sparse_matrix" ],
      [ "SpatialDiscretization", "dd/d1d/classchi__math_1_1_spatial_discretization.html", "dd/d1d/classchi__math_1_1_spatial_discretization" ],
      [ "SpatialDiscretization_FE", "d5/d3e/classchi__math_1_1_spatial_discretization___f_e.html", "d5/d3e/classchi__math_1_1_spatial_discretization___f_e" ],
      [ "SpatialDiscretization_FV", "d0/d9a/classchi__math_1_1_spatial_discretization___f_v.html", "d0/d9a/classchi__math_1_1_spatial_discretization___f_v" ],
      [ "SpatialDiscretization_PWLBase", "d1/dd0/classchi__math_1_1_spatial_discretization___p_w_l_base.html", "d1/dd0/classchi__math_1_1_spatial_discretization___p_w_l_base" ],
      [ "SpatialDiscretization_PWLC", "d4/da5/classchi__math_1_1_spatial_discretization___p_w_l_c.html", "d4/da5/classchi__math_1_1_spatial_discretization___p_w_l_c" ],
      [ "SpatialDiscretization_PWLD", "d3/d53/classchi__math_1_1_spatial_discretization___p_w_l_d.html", "d3/d53/classchi__math_1_1_spatial_discretization___p_w_l_d" ],
      [ "SphericalAngularQuadrature", "de/de3/classchi__math_1_1_spherical_angular_quadrature.html", "de/de3/classchi__math_1_1_spherical_angular_quadrature" ],
      [ "TensorRNX", "d1/dbe/structchi__math_1_1_tensor_r_n_x.html", "d1/dbe/structchi__math_1_1_tensor_r_n_x" ],
      [ "TensorRNX< 2, N, NumberFormat >", "d5/d52/structchi__math_1_1_tensor_r_n_x_3_012_00_01_n_00_01_number_format_01_4.html", "d5/d52/structchi__math_1_1_tensor_r_n_x_3_012_00_01_n_00_01_number_format_01_4" ],
      [ "Unknown", "d8/df3/classchi__math_1_1_unknown.html", "d8/df3/classchi__math_1_1_unknown" ],
      [ "UnknownManager", "d9/da7/classchi__math_1_1_unknown_manager.html", "d9/da7/classchi__math_1_1_unknown_manager" ],
      [ "VectorGhostCommunicator", "d1/db0/classchi__math_1_1_vector_ghost_communicator.html", "d1/db0/classchi__math_1_1_vector_ghost_communicator" ],
      [ "VectorNX", "d5/d8e/structchi__math_1_1_vector_n_x.html", "d5/d8e/structchi__math_1_1_vector_n_x" ]
    ] ],
    [ "chi_mesh", "d0/d81/namespacechi__mesh.html", [
      [ "mesh_cutting", "da/d62/namespacechi__mesh_1_1mesh__cutting.html", [
        [ "ECI", "d0/d45/structchi__mesh_1_1mesh__cutting_1_1_e_c_i.html", "d0/d45/structchi__mesh_1_1mesh__cutting_1_1_e_c_i" ]
      ] ],
      [ "sweep_management", "d7/dc7/namespacechi__mesh_1_1sweep__management.html", [
        [ "AngleAggregation", "d2/d3d/classchi__mesh_1_1sweep__management_1_1_angle_aggregation.html", "d2/d3d/classchi__mesh_1_1sweep__management_1_1_angle_aggregation" ],
        [ "AngleSet", "d1/de8/classchi__mesh_1_1sweep__management_1_1_angle_set.html", "d1/de8/classchi__mesh_1_1sweep__management_1_1_angle_set" ],
        [ "AngleSetGroup", "df/db6/classchi__mesh_1_1sweep__management_1_1_angle_set_group.html", "df/db6/classchi__mesh_1_1sweep__management_1_1_angle_set_group" ],
        [ "AUX_FLUDS", "d8/d3e/classchi__mesh_1_1sweep__management_1_1_a_u_x___f_l_u_d_s.html", "d8/d3e/classchi__mesh_1_1sweep__management_1_1_a_u_x___f_l_u_d_s" ],
        [ "BoundaryFunction", "d3/d51/classchi__mesh_1_1sweep__management_1_1_boundary_function.html", "d3/d51/classchi__mesh_1_1sweep__management_1_1_boundary_function" ],
        [ "BoundaryIncidentHeterogeneous", "d8/da9/classchi__mesh_1_1sweep__management_1_1_boundary_incident_heterogeneous.html", "d8/da9/classchi__mesh_1_1sweep__management_1_1_boundary_incident_heterogeneous" ],
        [ "BoundaryIsotropicHomogenous", "d0/dbe/classchi__mesh_1_1sweep__management_1_1_boundary_isotropic_homogenous.html", "d0/dbe/classchi__mesh_1_1sweep__management_1_1_boundary_isotropic_homogenous" ],
        [ "BoundaryReflecting", "d2/d07/classchi__mesh_1_1sweep__management_1_1_boundary_reflecting.html", "d2/d07/classchi__mesh_1_1sweep__management_1_1_boundary_reflecting" ],
        [ "BoundaryVaccuum", "d1/de0/classchi__mesh_1_1sweep__management_1_1_boundary_vaccuum.html", "d1/de0/classchi__mesh_1_1sweep__management_1_1_boundary_vaccuum" ],
        [ "FaceNodalMapping", "d7/d1f/structchi__mesh_1_1sweep__management_1_1_face_nodal_mapping.html", "d7/d1f/structchi__mesh_1_1sweep__management_1_1_face_nodal_mapping" ],
        [ "FLUDS", "de/da5/classchi__mesh_1_1sweep__management_1_1_f_l_u_d_s.html", "de/da5/classchi__mesh_1_1sweep__management_1_1_f_l_u_d_s" ],
        [ "INCOMING_FACE_INFO", "d8/daf/structchi__mesh_1_1sweep__management_1_1_i_n_c_o_m_i_n_g___f_a_c_e___i_n_f_o.html", "d8/daf/structchi__mesh_1_1sweep__management_1_1_i_n_c_o_m_i_n_g___f_a_c_e___i_n_f_o" ],
        [ "PRIMARY_FLUDS", "d9/d22/classchi__mesh_1_1sweep__management_1_1_p_r_i_m_a_r_y___f_l_u_d_s.html", "d9/d22/classchi__mesh_1_1sweep__management_1_1_p_r_i_m_a_r_y___f_l_u_d_s" ],
        [ "SPDS", "dc/d7b/structchi__mesh_1_1sweep__management_1_1_s_p_d_s.html", "dc/d7b/structchi__mesh_1_1sweep__management_1_1_s_p_d_s" ],
        [ "SPLS", "d5/d51/structchi__mesh_1_1sweep__management_1_1_s_p_l_s.html", "d5/d51/structchi__mesh_1_1sweep__management_1_1_s_p_l_s" ],
        [ "STDG", "df/dda/structchi__mesh_1_1sweep__management_1_1_s_t_d_g.html", "df/dda/structchi__mesh_1_1sweep__management_1_1_s_t_d_g" ],
        [ "SweepBoundary", "d9/d83/classchi__mesh_1_1sweep__management_1_1_sweep_boundary.html", "d9/d83/classchi__mesh_1_1sweep__management_1_1_sweep_boundary" ],
        [ "SweepBuffer", "dc/d15/classchi__mesh_1_1sweep__management_1_1_sweep_buffer.html", "dc/d15/classchi__mesh_1_1sweep__management_1_1_sweep_buffer" ],
        [ "SweepChunk", "d3/dfd/classchi__mesh_1_1sweep__management_1_1_sweep_chunk.html", "d3/dfd/classchi__mesh_1_1sweep__management_1_1_sweep_chunk" ],
        [ "SweepScheduler", "d1/d27/classchi__mesh_1_1sweep__management_1_1_sweep_scheduler.html", "d1/d27/classchi__mesh_1_1sweep__management_1_1_sweep_scheduler" ]
      ] ],
      [ "BooleanLogicalVolume", "da/dca/classchi__mesh_1_1_boolean_logical_volume.html", "da/dca/classchi__mesh_1_1_boolean_logical_volume" ],
      [ "Cell", "d8/d7c/classchi__mesh_1_1_cell.html", "d8/d7c/classchi__mesh_1_1_cell" ],
      [ "CellFace", "db/d1b/classchi__mesh_1_1_cell_face.html", "db/d1b/classchi__mesh_1_1_cell_face" ],
      [ "Edge", "d9/d36/structchi__mesh_1_1_edge.html", "d9/d36/structchi__mesh_1_1_edge" ],
      [ "Face", "d4/dd2/structchi__mesh_1_1_face.html", "d4/dd2/structchi__mesh_1_1_face" ],
      [ "FFICellIntersection", "dd/d9c/structchi__mesh_1_1_f_f_i_cell_intersection.html", "dd/d9c/structchi__mesh_1_1_f_f_i_cell_intersection" ],
      [ "FFIFaceEdgeIntersection", "d5/d06/structchi__mesh_1_1_f_f_i_face_edge_intersection.html", "d5/d06/structchi__mesh_1_1_f_f_i_face_edge_intersection" ],
      [ "FieldFunctionContext", "d3/d97/structchi__mesh_1_1_field_function_context.html", "d3/d97/structchi__mesh_1_1_field_function_context" ],
      [ "FieldFunctionInterpolation", "d5/dd4/classchi__mesh_1_1_field_function_interpolation.html", "d5/dd4/classchi__mesh_1_1_field_function_interpolation" ],
      [ "FieldFunctionInterpolationLine", "d5/d14/classchi__mesh_1_1_field_function_interpolation_line.html", "d5/d14/classchi__mesh_1_1_field_function_interpolation_line" ],
      [ "FieldFunctionInterpolationPoint", "d6/d29/classchi__mesh_1_1_field_function_interpolation_point.html", "d6/d29/classchi__mesh_1_1_field_function_interpolation_point" ],
      [ "FieldFunctionInterpolationSlice", "d4/d6b/classchi__mesh_1_1_field_function_interpolation_slice.html", "d4/d6b/classchi__mesh_1_1_field_function_interpolation_slice" ],
      [ "FieldFunctionInterpolationVolume", "db/dd5/classchi__mesh_1_1_field_function_interpolation_volume.html", "db/dd5/classchi__mesh_1_1_field_function_interpolation_volume" ],
      [ "GlobalCellHandler", "d7/d24/classchi__mesh_1_1_global_cell_handler.html", "d7/d24/classchi__mesh_1_1_global_cell_handler" ],
      [ "GridFaceHistogram", "d1/df6/classchi__mesh_1_1_grid_face_histogram.html", "d1/df6/classchi__mesh_1_1_grid_face_histogram" ],
      [ "LocalCellHandler", "d7/d36/classchi__mesh_1_1_local_cell_handler.html", "d7/d36/classchi__mesh_1_1_local_cell_handler" ],
      [ "LogicalVolume", "d0/d1e/classchi__mesh_1_1_logical_volume.html", "d0/d1e/classchi__mesh_1_1_logical_volume" ],
      [ "Matrix3x3", "d0/dec/structchi__mesh_1_1_matrix3x3.html", "d0/dec/structchi__mesh_1_1_matrix3x3" ],
      [ "MeshContinuum", "d3/d1c/classchi__mesh_1_1_mesh_continuum.html", "d3/d1c/classchi__mesh_1_1_mesh_continuum" ],
      [ "MeshHandler", "d2/d10/classchi__mesh_1_1_mesh_handler.html", "d2/d10/classchi__mesh_1_1_mesh_handler" ],
      [ "PolyFace", "d4/ddb/structchi__mesh_1_1_poly_face.html", "d4/ddb/structchi__mesh_1_1_poly_face" ],
      [ "RayTracer", "dd/d2a/classchi__mesh_1_1_ray_tracer.html", "dd/d2a/classchi__mesh_1_1_ray_tracer" ],
      [ "RayTracerOutputInformation", "da/d07/structchi__mesh_1_1_ray_tracer_output_information.html", "da/d07/structchi__mesh_1_1_ray_tracer_output_information" ],
      [ "RCCLogicalVolume", "dc/d7c/classchi__mesh_1_1_r_c_c_logical_volume.html", "dc/d7c/classchi__mesh_1_1_r_c_c_logical_volume" ],
      [ "RPPLogicalVolume", "d4/dea/classchi__mesh_1_1_r_p_p_logical_volume.html", "d4/dea/classchi__mesh_1_1_r_p_p_logical_volume" ],
      [ "SphereLogicalVolume", "db/d06/classchi__mesh_1_1_sphere_logical_volume.html", "db/d06/classchi__mesh_1_1_sphere_logical_volume" ],
      [ "SurfaceMesh", "dd/d43/classchi__mesh_1_1_surface_mesh.html", "dd/d43/classchi__mesh_1_1_surface_mesh" ],
      [ "SurfaceMesher", "df/d7e/classchi__mesh_1_1_surface_mesher.html", "df/d7e/classchi__mesh_1_1_surface_mesher" ],
      [ "SurfaceMesherPassthrough", "d3/d2d/classchi__mesh_1_1_surface_mesher_passthrough.html", "d3/d2d/classchi__mesh_1_1_surface_mesher_passthrough" ],
      [ "SurfaceMesherPredefined", "d0/d83/classchi__mesh_1_1_surface_mesher_predefined.html", "d0/d83/classchi__mesh_1_1_surface_mesher_predefined" ],
      [ "SurfaceMeshLogicalVolume", "dd/ddb/classchi__mesh_1_1_surface_mesh_logical_volume.html", "dd/ddb/classchi__mesh_1_1_surface_mesh_logical_volume" ],
      [ "TensorRank2Dim3", "d8/d2c/structchi__mesh_1_1_tensor_rank2_dim3.html", "d8/d2c/structchi__mesh_1_1_tensor_rank2_dim3" ],
      [ "UnpartitionedMesh", "d4/d7b/classchi__mesh_1_1_unpartitioned_mesh.html", "d4/d7b/classchi__mesh_1_1_unpartitioned_mesh" ],
      [ "Vector3", "dd/d54/structchi__mesh_1_1_vector3.html", "dd/d54/structchi__mesh_1_1_vector3" ],
      [ "VertexHandler", "d1/d59/classchi__mesh_1_1_vertex_handler.html", "d1/d59/classchi__mesh_1_1_vertex_handler" ],
      [ "VolumeMesher", "de/df0/classchi__mesh_1_1_volume_mesher.html", "de/df0/classchi__mesh_1_1_volume_mesher" ],
      [ "VolumeMesherExtruder", "de/d89/classchi__mesh_1_1_volume_mesher_extruder.html", "de/d89/classchi__mesh_1_1_volume_mesher_extruder" ],
      [ "VolumeMesherPredefinedUnpartitioned", "dd/d06/classchi__mesh_1_1_volume_mesher_predefined_unpartitioned.html", "dd/d06/classchi__mesh_1_1_volume_mesher_predefined_unpartitioned" ]
    ] ],
    [ "chi_objects", "d1/d96/namespacechi__objects.html", [
      [ "ChiConsole", "d0/dc4/classchi__objects_1_1_chi_console.html", "d0/dc4/classchi__objects_1_1_chi_console" ],
      [ "ChiLog", "d8/d42/classchi__objects_1_1_chi_log.html", "d8/d42/classchi__objects_1_1_chi_log" ],
      [ "ChiMPICommunicatorSet", "d8/da3/classchi__objects_1_1_chi_m_p_i_communicator_set.html", "d8/da3/classchi__objects_1_1_chi_m_p_i_communicator_set" ],
      [ "ChiTimer", "d1/d87/classchi__objects_1_1_chi_timer.html", "d1/d87/classchi__objects_1_1_chi_timer" ],
      [ "CSTMemory", "dd/d68/structchi__objects_1_1_c_s_t_memory.html", "dd/d68/structchi__objects_1_1_c_s_t_memory" ],
      [ "DummyStream", "d7/d40/structchi__objects_1_1_dummy_stream.html", "d7/d40/structchi__objects_1_1_dummy_stream" ],
      [ "LogStream", "dc/d75/classchi__objects_1_1_log_stream.html", "dc/d75/classchi__objects_1_1_log_stream" ],
      [ "MPI_Info", "d2/d8e/classchi__objects_1_1_m_p_i___info.html", "d2/d8e/classchi__objects_1_1_m_p_i___info" ]
    ] ],
    [ "chi_physics", "d6/d5f/namespacechi__physics.html", [
      [ "AdjointMGXS", "df/d62/classchi__physics_1_1_adjoint_m_g_x_s.html", "df/d62/classchi__physics_1_1_adjoint_m_g_x_s" ],
      [ "BasicOption", "d2/dd8/classchi__physics_1_1_basic_option.html", "d2/dd8/classchi__physics_1_1_basic_option" ],
      [ "BasicOptions", "d1/d7c/classchi__physics_1_1_basic_options.html", "d1/d7c/classchi__physics_1_1_basic_options" ],
      [ "FieldFunction", "df/de9/classchi__physics_1_1_field_function.html", "df/de9/classchi__physics_1_1_field_function" ],
      [ "IsotropicMultiGrpSource", "dc/d04/classchi__physics_1_1_isotropic_multi_grp_source.html", "dc/d04/classchi__physics_1_1_isotropic_multi_grp_source" ],
      [ "Material", "d8/da4/classchi__physics_1_1_material.html", "d8/da4/classchi__physics_1_1_material" ],
      [ "MaterialProperty", "df/d52/classchi__physics_1_1_material_property.html", "df/d52/classchi__physics_1_1_material_property" ],
      [ "MultiGroupXS", "df/db7/classchi__physics_1_1_multi_group_x_s.html", "df/db7/classchi__physics_1_1_multi_group_x_s" ],
      [ "ScalarValue", "db/d6e/classchi__physics_1_1_scalar_value.html", "db/d6e/classchi__physics_1_1_scalar_value" ],
      [ "SingleStateMGXS", "de/dc9/classchi__physics_1_1_single_state_m_g_x_s.html", "de/dc9/classchi__physics_1_1_single_state_m_g_x_s" ],
      [ "Solver", "d9/d3a/classchi__physics_1_1_solver.html", "d9/d3a/classchi__physics_1_1_solver" ]
    ] ],
    [ "dfem_diffusion", "dc/dbe/namespacedfem__diffusion.html", [
      [ "Boundary", "dd/d4b/classdfem__diffusion_1_1_boundary.html", "dd/d4b/classdfem__diffusion_1_1_boundary" ],
      [ "Solver", "df/ddc/classdfem__diffusion_1_1_solver.html", "df/ddc/classdfem__diffusion_1_1_solver" ]
    ] ],
    [ "fv_diffusion", "dc/dfe/namespacefv__diffusion.html", [
      [ "Boundary", "d2/df4/classfv__diffusion_1_1_boundary.html", "d2/df4/classfv__diffusion_1_1_boundary" ],
      [ "Solver", "d1/dd1/classfv__diffusion_1_1_solver.html", "d1/dd1/classfv__diffusion_1_1_solver" ]
    ] ],
    [ "lbs", "d9/d42/namespacelbs.html", [
      [ "acceleration", "d8/d43/namespacelbs_1_1acceleration.html", [
        [ "BoundaryCondition", "d5/df7/structlbs_1_1acceleration_1_1_boundary_condition.html", "d5/df7/structlbs_1_1acceleration_1_1_boundary_condition" ],
        [ "DiffusionMIPSolver", "d0/d34/classlbs_1_1acceleration_1_1_diffusion_m_i_p_solver.html", "d0/d34/classlbs_1_1acceleration_1_1_diffusion_m_i_p_solver" ],
        [ "Multigroup_D_and_sigR", "d6/d81/structlbs_1_1acceleration_1_1_multigroup___d__and__sig_r.html", "d6/d81/structlbs_1_1acceleration_1_1_multigroup___d__and__sig_r" ],
        [ "NLKEigenDiffContext", "d3/d65/structlbs_1_1acceleration_1_1_n_l_k_eigen_diff_context.html", "d3/d65/structlbs_1_1acceleration_1_1_n_l_k_eigen_diff_context" ],
        [ "NLKEigenDiffSolver", "d7/d3b/classlbs_1_1acceleration_1_1_n_l_k_eigen_diff_solver.html", "d7/d3b/classlbs_1_1acceleration_1_1_n_l_k_eigen_diff_solver" ],
        [ "TwoGridCollapsedInfo", "db/d99/structlbs_1_1acceleration_1_1_two_grid_collapsed_info.html", "db/d99/structlbs_1_1acceleration_1_1_two_grid_collapsed_info" ]
      ] ],
      [ "AdjointSourceFunction", "d8/d7e/classlbs_1_1_adjoint_source_function.html", "d8/d7e/classlbs_1_1_adjoint_source_function" ],
      [ "AGSContext", "d4/d2a/structlbs_1_1_a_g_s_context.html", "d4/d2a/structlbs_1_1_a_g_s_context" ],
      [ "AGSLinearSolver", "d9/df9/classlbs_1_1_a_g_s_linear_solver.html", "d9/df9/classlbs_1_1_a_g_s_linear_solver" ],
      [ "AGSSchemeEntry", "d9/d24/classlbs_1_1_a_g_s_scheme_entry.html", "d9/d24/classlbs_1_1_a_g_s_scheme_entry" ],
      [ "BoundaryFunctionToLua", "d6/dd3/classlbs_1_1_boundary_function_to_lua.html", "d6/dd3/classlbs_1_1_boundary_function_to_lua" ],
      [ "BoundaryPreference", "d4/d8e/structlbs_1_1_boundary_preference.html", "d4/d8e/structlbs_1_1_boundary_preference" ],
      [ "CellLBSView", "d4/d32/classlbs_1_1_cell_l_b_s_view.html", "d4/d32/classlbs_1_1_cell_l_b_s_view" ],
      [ "DiscOrdKEigenvalueSolver", "d4/dd0/classlbs_1_1_disc_ord_k_eigenvalue_solver.html", "d4/dd0/classlbs_1_1_disc_ord_k_eigenvalue_solver" ],
      [ "DiscOrdSteadyStateAdjointSolver", "d6/d0f/classlbs_1_1_disc_ord_steady_state_adjoint_solver.html", "d6/d0f/classlbs_1_1_disc_ord_steady_state_adjoint_solver" ],
      [ "DiscOrdSteadyStateSolver", "dd/d4b/classlbs_1_1_disc_ord_steady_state_solver.html", "dd/d4b/classlbs_1_1_disc_ord_steady_state_solver" ],
      [ "DiscOrdTransientSolver", "d6/d7b/classlbs_1_1_disc_ord_transient_solver.html", "d6/d7b/classlbs_1_1_disc_ord_transient_solver" ],
      [ "KResidualFunctionContext", "d7/d94/structlbs_1_1_k_residual_function_context.html", "d7/d94/structlbs_1_1_k_residual_function_context" ],
      [ "LBSDiscreteOrdinatesSolver", "d4/d0b/classlbs_1_1_l_b_s_discrete_ordinates_solver.html", "d4/d0b/classlbs_1_1_l_b_s_discrete_ordinates_solver" ],
      [ "LBSGroup", "d5/d86/classlbs_1_1_l_b_s_group.html", "d5/d86/classlbs_1_1_l_b_s_group" ],
      [ "LBSGroupset", "d2/db6/classlbs_1_1_l_b_s_groupset.html", "d2/db6/classlbs_1_1_l_b_s_groupset" ],
      [ "LBSSolver", "dc/db7/classlbs_1_1_l_b_s_solver.html", "dc/db7/classlbs_1_1_l_b_s_solver" ],
      [ "MIPSteadyStateSolver", "d5/d5f/classlbs_1_1_m_i_p_steady_state_solver.html", "d5/d5f/classlbs_1_1_m_i_p_steady_state_solver" ],
      [ "MIPWGSContext", "d4/dd2/structlbs_1_1_m_i_p_w_g_s_context.html", "d4/dd2/structlbs_1_1_m_i_p_w_g_s_context" ],
      [ "NLKEigenAGSContext", "dc/d17/structlbs_1_1_n_l_k_eigen_a_g_s_context.html", "dc/d17/structlbs_1_1_n_l_k_eigen_a_g_s_context" ],
      [ "NLKEigenvalueAGSSolver", "d0/d0b/classlbs_1_1_n_l_k_eigenvalue_a_g_s_solver.html", "d0/d0b/classlbs_1_1_n_l_k_eigenvalue_a_g_s_solver" ],
      [ "Options", "dc/dcd/structlbs_1_1_options.html", "dc/dcd/structlbs_1_1_options" ],
      [ "PointSource", "dc/d4f/classlbs_1_1_point_source.html", "dc/d4f/classlbs_1_1_point_source" ],
      [ "ResponseFunctionDesignation", "d6/d34/structlbs_1_1_response_function_designation.html", "d6/d34/structlbs_1_1_response_function_designation" ],
      [ "SourceFunction", "dc/d64/classlbs_1_1_source_function.html", "dc/d64/classlbs_1_1_source_function" ],
      [ "SubSetInfo", "da/d31/structlbs_1_1_sub_set_info.html", "da/d31/structlbs_1_1_sub_set_info" ],
      [ "SweepChunkPWL", "d0/d5c/classlbs_1_1_sweep_chunk_p_w_l.html", "d0/d5c/classlbs_1_1_sweep_chunk_p_w_l" ],
      [ "SweepChunkPWLTransientTheta", "d8/da5/classlbs_1_1_sweep_chunk_p_w_l_transient_theta.html", "d8/da5/classlbs_1_1_sweep_chunk_p_w_l_transient_theta" ],
      [ "SweepWGSContext", "d9/df7/structlbs_1_1_sweep_w_g_s_context.html", "d9/df7/structlbs_1_1_sweep_w_g_s_context" ],
      [ "TransientSourceFunction", "dc/d71/classlbs_1_1_transient_source_function.html", "dc/d71/classlbs_1_1_transient_source_function" ],
      [ "UnitCellMatrices", "dc/d37/structlbs_1_1_unit_cell_matrices.html", "dc/d37/structlbs_1_1_unit_cell_matrices" ],
      [ "WGSContext", "dd/ddd/structlbs_1_1_w_g_s_context.html", "dd/ddd/structlbs_1_1_w_g_s_context" ],
      [ "WGSLinearSolver", "d7/d8c/classlbs_1_1_w_g_s_linear_solver.html", "d7/d8c/classlbs_1_1_w_g_s_linear_solver" ]
    ] ],
    [ "lbs_curvilinear", "dc/dad/namespacelbs__curvilinear.html", [
      [ "DiscOrdSteadyStateSolver", "df/de3/classlbs__curvilinear_1_1_disc_ord_steady_state_solver.html", "df/de3/classlbs__curvilinear_1_1_disc_ord_steady_state_solver" ],
      [ "SweepChunkPWL", "d2/df7/classlbs__curvilinear_1_1_sweep_chunk_p_w_l.html", "d2/df7/classlbs__curvilinear_1_1_sweep_chunk_p_w_l" ]
    ] ],
    [ "mg_diffusion", "df/dd2/namespacemg__diffusion.html", [
      [ "Boundary", "d6/dea/classmg__diffusion_1_1_boundary.html", "d6/dea/classmg__diffusion_1_1_boundary" ],
      [ "KSPAppContext", "dc/da1/structmg__diffusion_1_1_k_s_p_app_context.html", "dc/da1/structmg__diffusion_1_1_k_s_p_app_context" ],
      [ "Solver", "d4/d4c/classmg__diffusion_1_1_solver.html", "d4/d4c/classmg__diffusion_1_1_solver" ],
      [ "TwoGridCollapsedInfo", "d6/d5b/structmg__diffusion_1_1_two_grid_collapsed_info.html", "d6/d5b/structmg__diffusion_1_1_two_grid_collapsed_info" ]
    ] ],
    [ "chi", "d4/d35/classchi.html", "d4/d35/classchi" ],
    [ "vtkNew", "db/ddd/classvtk_new.html", null ],
    [ "vtkSmartPointer", "d5/d8c/classvtk_smart_pointer.html", null ]
];