var dir_e898430a5ef92fc0a20c944c995be969 =
[
    [ "CHI_REMESHEDSURFACE", "dir_74bcc2d8c135e555cd8e1c9c213f1ae8.html", "dir_74bcc2d8c135e555cd8e1c9c213f1ae8" ],
    [ "lua", "dir_22f7fb76556f551712a598e67dc8fbf6.html", "dir_22f7fb76556f551712a598e67dc8fbf6" ],
    [ "chi_surfaceremesher.h", "da/d4b/chi__surfaceremesher_8h.html", [
      [ "CHI_SURFACEREMESHER", "dd/da5/class_c_h_i___s_u_r_f_a_c_e_r_e_m_e_s_h_e_r.html", "dd/da5/class_c_h_i___s_u_r_f_a_c_e_r_e_m_e_s_h_e_r" ]
    ] ],
    [ "chi_surfaceremesher_structs.h", "d0/d23/chi__surfaceremesher__structs_8h.html", [
      [ "CHI_COLINEDGELIST", "dd/d4f/structchi_surface_meshing_1_1_c_h_i___c_o_l_i_n_e_d_g_e_l_i_s_t.html", "dd/d4f/structchi_surface_meshing_1_1_c_h_i___c_o_l_i_n_e_d_g_e_l_i_s_t" ],
      [ "CHI_EDGELOOP", "d6/d66/structchi_surface_meshing_1_1_c_h_i___e_d_g_e_l_o_o_p.html", "d6/d66/structchi_surface_meshing_1_1_c_h_i___e_d_g_e_l_o_o_p" ],
      [ "CHI_FACELIST", "d1/d2d/structchi_surface_meshing_1_1_c_h_i___f_a_c_e_l_i_s_t.html", "d1/d2d/structchi_surface_meshing_1_1_c_h_i___f_a_c_e_l_i_s_t" ],
      [ "CHI_PATCH", "df/d04/structchi_surface_meshing_1_1_c_h_i___p_a_t_c_h.html", "df/d04/structchi_surface_meshing_1_1_c_h_i___p_a_t_c_h" ],
      [ "CHI_OPENEDGE", "d0/d9b/structchi_surface_meshing_1_1_c_h_i___o_p_e_n_e_d_g_e.html", "d0/d9b/structchi_surface_meshing_1_1_c_h_i___o_p_e_n_e_d_g_e" ],
      [ "CHI_INTERIOREDGE", "d2/d65/structchi_surface_meshing_1_1_c_h_i___i_n_t_e_r_i_o_r_e_d_g_e.html", "d2/d65/structchi_surface_meshing_1_1_c_h_i___i_n_t_e_r_i_o_r_e_d_g_e" ],
      [ "CHI_TRIPLET_VERTEX", "df/d1b/structchi_surface_meshing_1_1_c_h_i___t_r_i_p_l_e_t___v_e_r_t_e_x.html", "df/d1b/structchi_surface_meshing_1_1_c_h_i___t_r_i_p_l_e_t___v_e_r_t_e_x" ]
    ] ],
    [ "chi_surfremesher_00_constrdestr.cpp", "dd/d31/chi__surfremesher__00__constrdestr_8cpp.html", null ],
    [ "chi_surfremesher_01_executemeshing.cpp", "de/dae/chi__surfremesher__01__executemeshing_8cpp.html", null ],
    [ "chi_surfremesher_02_s01_conplanfaces.cpp", "d4/de3/chi__surfremesher__02__s01__conplanfaces_8cpp.html", null ],
    [ "chi_surfremesher_02_s02_patchlist.cpp", "de/d98/chi__surfremesher__02__s02__patchlist_8cpp.html", null ],
    [ "chi_surfremesher_02_s03_openedges.cpp", "dd/d61/chi__surfremesher__02__s03__openedges_8cpp.html", null ],
    [ "chi_surfremesher_02_s04_colinear.cpp", "d2/d2e/chi__surfremesher__02__s04__colinear_8cpp.html", null ],
    [ "chi_surfremesher_02_s05_EdgeLoops.cpp", "d3/d5b/chi__surfremesher__02__s05___edge_loops_8cpp.html", null ],
    [ "chi_surfremesher_02_s06_essentialverts.cpp", "d4/da4/chi__surfremesher__02__s06__essentialverts_8cpp.html", null ],
    [ "chi_surfremesher_02_s07_copymeshtoremeshed.cpp", "db/dbc/chi__surfremesher__02__s07__copymeshtoremeshed_8cpp.html", null ],
    [ "chi_surfremesher_03_utilities.cpp", "d3/d26/chi__surfremesher__03__utilities_8cpp.html", null ],
    [ "chi_surfremesher_04_create2ddelaunay.cpp", "d5/d18/chi__surfremesher__04__create2ddelaunay_8cpp.html", null ],
    [ "chi_surfremesher_04a_project3dto2d.cpp", "d8/dd5/chi__surfremesher__04a__project3dto2d_8cpp.html", null ],
    [ "chi_surfremesher_04b_sortlexicographically.cpp", "da/dce/chi__surfremesher__04b__sortlexicographically_8cpp.html", null ],
    [ "chi_surfremesher_04c_createinitriangle.cpp", "d0/d0f/chi__surfremesher__04c__createinitriangle_8cpp.html", null ],
    [ "chi_surfremesher_04d_orient2d.cpp", "dc/d77/chi__surfremesher__04d__orient2d_8cpp.html", null ],
    [ "chi_surfremesher_04e_getunusedvertices.cpp", "d0/d76/chi__surfremesher__04e__getunusedvertices_8cpp.html", null ],
    [ "chi_surfremesher_04f_attachunusedvertex.cpp", "d2/d1c/chi__surfremesher__04f__attachunusedvertex_8cpp.html", null ],
    [ "chi_surfremesher_04g_convexifyhull.cpp", "d1/d7c/chi__surfremesher__04g__convexifyhull_8cpp.html", null ],
    [ "chi_surfremesher_04h_incircle.cpp", "d3/dd9/chi__surfremesher__04h__incircle_8cpp.html", null ],
    [ "chi_surfremesher_04i_listnonlocaldeledges.cpp", "d4/d00/chi__surfremesher__04i__listnonlocaldeledges_8cpp.html", null ],
    [ "chi_surfremesher_04j_edgeflip.cpp", "d6/dc3/chi__surfremesher__04j__edgeflip_8cpp.html", null ],
    [ "chi_surfremesher_05_refineedgesize.cpp", "df/d8d/chi__surfremesher__05__refineedgesize_8cpp.html", null ],
    [ "chi_surfremesher_05_refinepatchmesh.cpp", "d6/d7c/chi__surfremesher__05__refinepatchmesh_8cpp.html", null ],
    [ "chi_surfremesher_05_restoreoptimality.cpp", "d6/dc0/chi__surfremesher__05__restoreoptimality_8cpp.html", null ],
    [ "chi_surfremesher_05a_makedelaunay.cpp", "d9/de7/chi__surfremesher__05a__makedelaunay_8cpp.html", null ],
    [ "chi_surfremesher_05b_findencroachedsubseg.cpp", "d3/dc3/chi__surfremesher__05b__findencroachedsubseg_8cpp.html", null ],
    [ "chi_surfremesher_05c_removeencroachedges.cpp", "de/dc2/chi__surfremesher__05c__removeencroachedges_8cpp.html", null ],
    [ "chi_surfremesher_05d_splitsubsegment.cpp", "da/d45/chi__surfremesher__05d__splitsubsegment_8cpp.html", null ],
    [ "chi_surfremesher_05e_findsmallrhotris.cpp", "d6/db4/chi__surfremesher__05e__findsmallrhotris_8cpp.html", null ],
    [ "chi_surfremesher_05f_splittriangle.cpp", "d7/d5e/chi__surfremesher__05f__splittriangle_8cpp.html", null ],
    [ "chi_surfremesher_05g_insertvertex.cpp", "d3/dd9/chi__surfremesher__05g__insertvertex_8cpp.html", null ],
    [ "chi_surfremesher_05h_deletevertex.cpp", "d0/dcd/chi__surfremesher__05h__deletevertex_8cpp.html", null ]
];