var dir_07a40203f208a441997cef6053f575c7 =
[
    [ "diffusion_solver.h", "d9/d4b/diffusion__solver_8h.html", "d9/d4b/diffusion__solver_8h" ],
    [ "diffusion_solver_00_constrdestr.cc", "da/daa/diffusion__solver__00__constrdestr_8cc.html", null ],
    [ "diffusion_solver_01_general.cc", "db/d51/diffusion__solver__01__general_8cc.html", "db/d51/diffusion__solver__01__general_8cc" ],
    [ "diffusion_solver_01a_initstuff.cc", "db/d44/diffusion__solver__01a__initstuff_8cc.html", "db/d44/diffusion__solver__01a__initstuff_8cc" ],
    [ "diffusion_solver_01b_init.cc", "d3/db7/diffusion__solver__01b__init_8cc.html", "d3/db7/diffusion__solver__01b__init_8cc" ],
    [ "diffusion_solver_01c_init_pwlc.cc", "df/df4/diffusion__solver__01c__init__pwlc_8cc.html", "df/df4/diffusion__solver__01c__init__pwlc_8cc" ],
    [ "diffusion_solver_01d_init_pwld.cc", "d5/dd8/diffusion__solver__01d__init__pwld_8cc.html", "d5/dd8/diffusion__solver__01d__init__pwld_8cc" ],
    [ "diffusion_solver_01e_initpwld_grps.cc", "dd/df6/diffusion__solver__01e__initpwld__grps_8cc.html", "dd/df6/diffusion__solver__01e__initpwld__grps_8cc" ],
    [ "diffusion_solver_01f_initpwld_grpagg.cc", "d5/d42/diffusion__solver__01f__initpwld__grpagg_8cc.html", "d5/d42/diffusion__solver__01f__initpwld__grpagg_8cc" ],
    [ "diffusion_solver_02a_exec.cc", "d3/d6a/diffusion__solver__02a__exec_8cc.html", "d3/d6a/diffusion__solver__02a__exec_8cc" ],
    [ "diffusion_solver_02b_exec_pwlc.cc", "d6/db2/diffusion__solver__02b__exec__pwlc_8cc.html", "d6/db2/diffusion__solver__02b__exec__pwlc_8cc" ],
    [ "diffusion_solver_02b_pwlc_a_slab.cc", "db/d2f/diffusion__solver__02b__pwlc__a__slab_8cc.html", null ],
    [ "diffusion_solver_02b_pwlc_b_polygon.cc", "d0/df8/diffusion__solver__02b__pwlc__b__polygon_8cc.html", null ],
    [ "diffusion_solver_02b_pwlc_c_polyhedron.cc", "dc/de7/diffusion__solver__02b__pwlc__c__polyhedron_8cc.html", null ],
    [ "diffusion_solver_02c_exec_pwld_mip.cc", "da/da2/diffusion__solver__02c__exec__pwld__mip_8cc.html", "da/da2/diffusion__solver__02c__exec__pwld__mip_8cc" ],
    [ "diffusion_solver_02c_pwld_a_slab.cc", "d6/d9a/diffusion__solver__02c__pwld__a__slab_8cc.html", null ],
    [ "diffusion_solver_02c_pwld_b_polygon.cc", "d3/d6d/diffusion__solver__02c__pwld__b__polygon_8cc.html", null ],
    [ "diffusion_solver_02c_pwld_c_polyhedron.cc", "de/d41/diffusion__solver__02c__pwld__c__polyhedron_8cc.html", null ],
    [ "diffusion_solver_02d_exec_pwld_mip_grps.cc", "d2/da8/diffusion__solver__02d__exec__pwld__mip__grps_8cc.html", "d2/da8/diffusion__solver__02d__exec__pwld__mip__grps_8cc" ],
    [ "diffusion_solver_02e_exec_pwld_mip_gagg.cc", "d2/d9d/diffusion__solver__02e__exec__pwld__mip__gagg_8cc.html", "d2/d9d/diffusion__solver__02e__exec__pwld__mip__gagg_8cc" ],
    [ "diffusion_solver_02e_pwld_a_slab_gagg.cc", "d2/d51/diffusion__solver__02e__pwld__a__slab__gagg_8cc.html", null ],
    [ "diffusion_solver_02e_pwld_b_polygon_gagg.cc", "dd/d8f/diffusion__solver__02e__pwld__b__polygon__gagg_8cc.html", null ],
    [ "diffusion_solver_02e_pwld_c_polyhedron_gagg.cc", "d9/de6/diffusion__solver__02e__pwld__c__polyhedron__gagg_8cc.html", null ],
    [ "diffusion_solver_03a_utils_pwlc.cc", "d0/de2/diffusion__solver__03a__utils__pwlc_8cc.html", "d0/de2/diffusion__solver__03a__utils__pwlc_8cc" ],
    [ "diffusion_solver_03b_utils_plwd.cc", "d4/dca/diffusion__solver__03b__utils__plwd_8cc.html", "d4/dca/diffusion__solver__03b__utils__plwd_8cc" ]
];