var namespacechi__math =
[
    [ "finite_element", "d3/d84/namespacechi__math_1_1finite__element.html", "d3/d84/namespacechi__math_1_1finite__element" ],
    [ "PETScUtils", "dc/d29/namespacechi__math_1_1_p_e_t_sc_utils.html", "dc/d29/namespacechi__math_1_1_p_e_t_sc_utils" ],
    [ "SimplifiedLDFESQ", "dd/d56/namespacechi__math_1_1_simplified_l_d_f_e_s_q.html", "dd/d56/namespacechi__math_1_1_simplified_l_d_f_e_s_q" ],
    [ "AngularQuadrature", "d8/dd9/classchi__math_1_1_angular_quadrature.html", "d8/dd9/classchi__math_1_1_angular_quadrature" ],
    [ "CDFSampler", "d5/ddf/classchi__math_1_1_c_d_f_sampler.html", "d5/ddf/classchi__math_1_1_c_d_f_sampler" ],
    [ "DMatrixNX", "d7/d71/classchi__math_1_1_d_matrix_n_x.html", "d7/d71/classchi__math_1_1_d_matrix_n_x" ],
    [ "DVectorNX", "da/d6e/classchi__math_1_1_d_vector_n_x.html", "da/d6e/classchi__math_1_1_d_vector_n_x" ],
    [ "ProductQuadrature", "d5/df7/classchi__math_1_1_product_quadrature.html", "d5/df7/classchi__math_1_1_product_quadrature" ],
    [ "Quadrature", "d3/dbf/classchi__math_1_1_quadrature.html", "d3/dbf/classchi__math_1_1_quadrature" ],
    [ "QuadratureConical", "da/d37/classchi__math_1_1_quadrature_conical.html", "da/d37/classchi__math_1_1_quadrature_conical" ],
    [ "QuadratureGaussChebyshev", "d4/de5/classchi__math_1_1_quadrature_gauss_chebyshev.html", "d4/de5/classchi__math_1_1_quadrature_gauss_chebyshev" ],
    [ "QuadratureGaussLegendre", "d3/d07/classchi__math_1_1_quadrature_gauss_legendre.html", "d3/d07/classchi__math_1_1_quadrature_gauss_legendre" ],
    [ "QuadratureHexahedron", "d2/d67/classchi__math_1_1_quadrature_hexahedron.html", "d2/d67/classchi__math_1_1_quadrature_hexahedron" ],
    [ "QuadratureJacobi", "d4/d17/classchi__math_1_1_quadrature_jacobi.html", "d4/d17/classchi__math_1_1_quadrature_jacobi" ],
    [ "QuadraturePointPhiTheta", "dc/d9c/structchi__math_1_1_quadrature_point_phi_theta.html", "dc/d9c/structchi__math_1_1_quadrature_point_phi_theta" ],
    [ "QuadratureQuadrilateral", "da/d04/classchi__math_1_1_quadrature_quadrilateral.html", "da/d04/classchi__math_1_1_quadrature_quadrilateral" ],
    [ "QuadratureTetrahedron", "d8/d57/classchi__math_1_1_quadrature_tetrahedron.html", "d8/d57/classchi__math_1_1_quadrature_tetrahedron" ],
    [ "QuadratureTriangle", "d0/d61/classchi__math_1_1_quadrature_triangle.html", "d0/d61/classchi__math_1_1_quadrature_triangle" ],
    [ "RandomNumberGenerator", "d9/d55/classchi__math_1_1_random_number_generator.html", "d9/d55/classchi__math_1_1_random_number_generator" ],
    [ "SparseMatrix", "de/d51/classchi__math_1_1_sparse_matrix.html", "de/d51/classchi__math_1_1_sparse_matrix" ],
    [ "TensorRNX", "d1/dbe/structchi__math_1_1_tensor_r_n_x.html", "d1/dbe/structchi__math_1_1_tensor_r_n_x" ],
    [ "TensorRNX< 2, N, NumberFormat >", "d5/d52/structchi__math_1_1_tensor_r_n_x_3_012_00_01_n_00_01_number_format_01_4.html", "d5/d52/structchi__math_1_1_tensor_r_n_x_3_012_00_01_n_00_01_number_format_01_4" ],
    [ "UnknownManager", "d9/da7/classchi__math_1_1_unknown_manager.html", "d9/da7/classchi__math_1_1_unknown_manager" ],
    [ "VectorNX", "d5/d8e/structchi__math_1_1_vector_n_x.html", "d5/d8e/structchi__math_1_1_vector_n_x" ]
];